[package]
name = "api"
version = "0.1.0"
edition = "2024"

[dependencies]
tauri = { workspace = true }
database = { path = "../database" }
annotations = { path= "../annotations" }
formats = { path = "../formats" }
types = { path = "../types" }
state = { path = "../state" }
